### ISSUE TITLE
stackhpc hardware managers fails to install

### ISSUE THREAD

**Issue by jovial** [stackhpc/stackhpc-image-elements#38]
The error was:

```
2021-11-17 13:26:56.112 | /tmp/in_target.d/install.d/62-stackhpc-hardware-managers: line 11: /usr/share/ironic-python-agent/venv/bin/pip: No such file or directory
```

Configuration:
```
ipa_build_dib_git_elements:
  - repo: "https://github.com/stackhpc/stackhpc-image-elements"
    local: "{{ source_checkout_path }}/stackhpc-image-elements"
    version: "master"
    elements_path: "elements"

# List of additional inspection collectors to run.
#ipa_collectors_extra:
ipa_collectors_extra:
  - "extra-hardware"
```

kayobe version: train
